#!/bin/bash

export PYTHONPATH="$PYTHONPATH":BaseLib:SisClient:.

TEST_DIR="./tests/tracker_ext_test"
PEER_DIR="."
FILE=Locality-Demo.mp4
PORT=8859
TORRENT=$FILE".tstream"

python SisClient/Tools/vodclient.py --directory=$TEST_DIR/vodclient --torrent=$TEST_DIR/files/$TORRENT -y 20000 -x 300
