#!/bin/bash

TEST_DIR="./tests/tracker_ext_test"
PEER_DIR="."
FILE=Locality-Demo.mp4
FILE2=kgan97.mpg
PORT=8859
TORRENT=$FILE".tstream"
TORRENT2=$FILE2".tstream"


cp $TEST_DIR/files/$TORRENT $TEST_DIR/tracker/$TORRENT
cp $TEST_DIR/files/$TORRENT2 $TEST_DIR/tracker/$TORRENT2
sh tracker.sh -t $TEST_DIR/tracker/ --url=http://localhost:$PORT/announce
