##################################################
# file: HAPService_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/bin/wsdl2py --complexType HAPEndpoint.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from HAPService_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
SisHAPPort_reportActivity = GED("http://hap.ws.sis.smoothit.eu/", "reportActivity").pyclass

SisHAPPort_reportActivityResponse = GED("http://hap.ws.sis.smoothit.eu/", "reportActivityResponse").pyclass


# Service Skeletons
class HAPService(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/sis/HAPEndpoint', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_reportActivity(self, ps, **kw):
        request = ps.Parse(SisHAPPort_reportActivity.typecode)
        return request,SisHAPPort_reportActivityResponse()

    soapAction[''] = 'soap_reportActivity'
    root[(SisHAPPort_reportActivity.typecode.nspname,SisHAPPort_reportActivity.typecode.pname)] = 'soap_reportActivity'

